---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ssaapiappdeployment
spec:
 replicas: 1
 selector: 
   matchLabels: 
     app: ssaapiapp
 template:
  metadata:
   name: ssaapiapp
   labels:
     app: ssaapiapp	 
  spec: 
    containers:
<<<<<<< HEAD
    - name: ssaapiappcontainer
      image: ssa-api-image
#      imagePullPolicy: Always
=======
    - name: ssaapicontainer
      image: 7256268/ssa-api:latest
      imagePullPolicy: Always
>>>>>>> d72401322d4081706fed313415e0899d64a83449
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: ssaapiappappservice
spec:
  type: LoadBalancer
  selector:
   app: ssaapiapp
  ports:
<<<<<<< HEAD
   - protocol: TCP
     port: 80
     targetPort: 8080
...
=======
   - port: 7000
     targetPort: 7000
...
>>>>>>> d72401322d4081706fed313415e0899d64a83449
