---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ssaapiappdeployment
spec:
 replicas: 2
 strategy:
  type: RollingUpdate
 selector: 
   matchLabels: 
     app: ssaapiapp
 template:
  metadata:
   name: ssaapiapp
   labels:
     app: ssaapiapp	 
  spec: 
    containers:
    - name: ssaapiappcontainer
      image: 7256268/ssa-api:1.0
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: ssaapiappappservice
spec:
  type: LoadBalancer
  selector:
   app: ssaapiapp
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
...
